authentication pages
dkumarjha999/blog-app pull request #1
Opened 2023-07-17 15:56 UTC by kumardeepak99

created an application to implement nextjs learning and concepts

2023-07-19 09:07 UTC, kool7 requested changes

2023-07-19 09:07 UTC, kool7 commented on app/__tests__/__fixtures__/authentication/index.ts
> +  invalidCredentials: {
Why not using faker to generate this?

2023-07-19 09:07 UTC, kool7 commented on app/__tests__/unit/apiServices.ts/AuthService.test.ts
> +const URL = API_URL + "users";
Try to put all const in a separate utility file

2023-07-19 10:42 UTC, kumardeepak99 commented on app/__tests__/__fixtures__/authentication/index.ts
> +  invalidCredentials: {
sure i will do that

2023-07-19 10:42 UTC, kumardeepak99 commented on app/__tests__/unit/apiServices.ts/AuthService.test.ts
> +const URL = API_URL + "users";
ok

2023-07-21 08:05 UTC, kool7 approved these changes
Looks good.

2025-09-20 07:00 UTC, merged